version: "3.7"
services:
  web:
    build:
      context: ./
      dockerfile: .dockers/Dockerfile
    container_name: devlaptop-web
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.dockers/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    expose:
      - "9000"
    networks:
      - devlaptop_net
  db:
    image: 'mysql:latest'
    container_name: devlaptop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devlaptop
      MYSQL_ROOT_PASSWORD: devlaptop
      MYSQL_PASSWORD: devlaptop
      MYSQL_USER: devlaptop
    volumes:
      - ./.dockers/mysql:/var/lib/mysql
      - ./.dockers/mysql:/etc/mysql/conf.d
    ports:
      - "3388:3306"
    networks:
      - devlaptop_net
  nginx:
    image: nginx:alpine
    container_name: devlaptop-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    links:
      - web
      - db
    volumes:
      - ./:/var/www
      - ./.dockers/nginx:/etc/nginx/conf.d/
      - ./.dockers/logs/nginx:/var/log/nginx
    networks:
      - devlaptop_net


networks:
  devlaptop_net:
    driver: bridge
